ktor:
  application:
    modules:
      - com.ite393group5.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  secret: "secretfornow"
  domain: "http://localhost:8080/"
  studentAudience: ["http://localhost:8080/", "mobile-client"]
  staffAudience: ["http://localhost:8080/", "web-client"]
  issuer: "http://localhost:8080/"
  realm: "UPang Registrar Development Realm"
postgres:
  url: "jdbc:postgresql://localhost:5432/postgresdb"
  user: postgres
  password: postgres


