ktor:
  application:
    modules:
      - com.ite393group5.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
postgres:
  url: "jdbc:postgresql://localhost:5432/postgresdb"
  user: postgres
  password: postgres


