services:
  postgres-db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-container
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgresdb
    networks:
      - postgres-network
    restart: on-failure
networks:
  postgres-network:
    driver: bridge
